export const components = [
  { title: "Accordion", href: "/components/accordion" },
  { title: "Alert", href: "/components/alert" },
  { title: "Annotation", href: "/components/annotation" },
  { title: "Article", href: "/components/article" },
  { title: "Aspect Ratio", href: "/components/aspect-ratio" },
  { title: "Badge", href: "/components/badge" },
  // { title: "Blob", href: "/components/blob" },
  { title: "Button", href: "/components/button" },
  { title: "Carousel", href: "/components/carousel" },
  { title: "Checkbox", href: "/components/checkbox" },
  { title: "Counter", href: "/components/counter" },
  { title: "Divider", href: "/components/divider" },
  { title: "Drawer", href: "/components/drawer" },
  { title: "Features", href: "/components/features" },
  { title: "Footer", href: "/components/footer" },
  { title: "Heroes", href: "/components/heroes" },
  { title: "Image Lazyload", href: "/components/image-lazyload" },
  { title: "List", href: "/components/list" },
  { title: "Masonry", href: "/components/masonry" },
  { title: "Modal", href: "/components/modal" },
  { title: "Navbar", href: "/components/navbar" },
  { title: "Notification", href: "/components/notification" },
  { title: "Page Transition", href: "/components/page-transition" },
  { title: "Pricing", href: "/components/pricing" },
  { title: "Products", href: "/components/products" },
  { title: "Progress", href: "/components/progress" },
  { title: "Rating", href: "/components/rating" },
  { title: "Slider", href: "/components/slider" },
  { title: "Slideshow", href: "/components/slideshow" },
  { title: "Statistics", href: "/components/statistics" },
  { title: "Steps", href: "/components/steps" },
  { title: "Sticky", href: "/components/sticky" },
  { title: "Switch", href: "/components/switch" },
  { title: "Table", href: "/components/table" },
  { title: "Tabs", href: "/components/tabs" },
  { title: "Tag", href: "/components/badge/#tags" },
  { title: "Team", href: "/components/team" },
  { title: "Testimonials", href: "/components/testimonials" },
  { title: "Timeline", href: "/components/timeline" },
  { title: "Toast", href: "/components/toast" },
];

export const newComponents: string[] = [];
